name: Jenkins-like Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    needs: [preparation]
    strategy:
      matrix:
        name: [JobA, JobB, JobC]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: prepData }
      - name: Run ${{ matrix.name }}
        run: |
          echo "${{ matrix.name }} running with $(cat prep.txt)" > ${{ matrix.name }}.log
          cat ${{ matrix.name }}.log
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}Data
          path: ${{ matrix.name }}.log
